### ISSUE TITLE
preferences panel

### ISSUE THREAD

**Issue by wbolster** [wbolster/nothing-to-say#1]
...to set the shortcuts, instead of using dconf.

**Comment by semente** [comment]
Options I would see in the preferences panel:

- [ ] Flag to turn indicator icon always visible
- [ ] Flag to automatically mute mic in startup/login
- [ ] Flag to automatically mute mic after recording finished

**Comment by wbolster** [comment]
see also #2, perhaps this could work with fewer toggles?

**Comment by semente** [comment]
I think flags 2 and 3 could be the same. I don't see a point to have it separated, you are right.

**Comment by wbolster** [comment]
yeah, agreed. but the actual first step would be to actually implement it ;)
