### ISSUE TITLE
Unable to get it working on GNOME Shell 3.24

### ISSUE THREAD

**Issue by jc00ke** [wbolster/nothing-to-say#10]
I've cloned this repo to `/home/jesse/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee` and I've added `3.24` to the `shell-version` list in `metadata.json` but the extension isn't being activated when my mic is activated.

Happy to help debug!

**Comment by jc00ke** [comment]
I lied. Turns out I can't to json correctly and I had a slight typo. I'll still issue a PR for the minor change though.

**Comment by wbolster** [comment]
thanks. the new version should be available from extensions.gnome.org now.
