### ISSUE TITLE
Hard to find on extensions.gnome.org

### ISSUE THREAD

**Issue by phw** [wbolster/nothing-to-say#13]
This is extension is awesome, and I really depend on it. But it is hard to find on extensions.gnome.org.

After a reinstall I could not remember the name of this extension, and searching for obvious keywords like "mute", "volume", "audio", "silence", "silent" did not find this extension ("microphone" would have worked).

**Comment by wbolster** [comment]
great to hear this extension is useful to you.

i added a bunch of keywords to the description on https://extensions.gnome.org/extension/1113/nothing-to-say/

> keywords: audio, call, conference, microphone, mute, noise, noisy, push to talk, record, recording, silence, silent, sound, speak, talk, teleconference, unmute, volume, walkie-talkie

let me know if you have further suggestions.
