### ISSUE TITLE
Icon don't shows on panel

### ISSUE THREAD

**Issue by RidgeA** [wbolster/nothing-to-say#14]
Hello!
I installed the extension and icon didn't appear on panel.

I'm using Fedora 27 with Gnome 3.26.2.
Please, let me know if you need more information about my issue.

Thanks!

**Comment by wbolster** [comment]
please read the readme. :) this is intentional.

**Comment by RidgeA** [comment]
Sorry, now I get it :-)

**Comment by wbolster** [comment]
no worries :)
