### ISSUE TITLE
Can't see the icon

### ISSUE THREAD

**Issue by cmdrkerman** [wbolster/nothing-to-say#17]
My microphone is connected and extension's shortcuts are working (tried to record myself and it worked great). But there is no icon in the panel. Other extensions work fine, so that's not the panel's fault. Maybe it's because i'm using USB microphone.

I'm using Solus 4.0 and GNOME Shell 3.28.3

And thank you for this extension. You saved my live.

**Comment by wbolster** [comment]
glad to hear the extension helps others as well!

by design, the icon is only visible when recording. see readme.

**Comment by cmdrkerman** [comment]
Oh, i totally misunderstood. Thanks!

**Comment by wbolster** [comment]
yw!
