### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by haeckle** [wbolster/nothing-to-say#18]
... or at least I couldn't find it.

Would be cool if this would be free software 😌

**Comment by wbolster** [comment]
yeah, it sure is. just slammed a gplv2 in the repo: 3089dc4df4e920d02c2fa6bc39456857bcd0258d

> license as gpl v2
>
> some code snippets originate from gnome-shell which is under the same
> license, so out of convenience just license the whole thing as gplv2
> despite my growing dislike of the gnu project's ineffective puritanism.

never got around to it and it went unnoticed for 4 years. out of curiosiy, any specific reason this caught your eye, @haeckle?

**Comment by haeckle** [comment]
No specific reason, I just stumbled upon it and thought I could ask.
