### ISSUE TITLE
Problem with gnome-shell 3.38

### ISSUE THREAD

**Issue by rudolfkastl** [wbolster/nothing-to-say#19]
No property x_fill on StBin.

Tested on upcoming Fedora 33.

**Comment by wbolster-eiq** [comment]
any idea what would be causing this? seems it still exists?

- https://developer.gnome.org/st/stable/StBin.html#StBin--x-fill
- https://developer.gnome.org/st/unstable/StBin.html#StBin--x-fill

**Comment by wbolster** [comment]
any idea what would be causing this? seems it still exists?

- https://developer.gnome.org/st/stable/StBin.html#StBin--x-fill
- https://developer.gnome.org/st/unstable/StBin.html#StBin--x-fill

**Comment by rudolfkastl** [comment]
function enable() {
  microphone = new Microphone();
  panel_icon = new St.Icon({
    icon_name: '',
    style_class: 'system-status-icon'});
  panel_button = new St.Bin({
    style_class: 'panel-button',
    reactive: true,
    can_focus: true,
    //x_fill: true,
    //y_fill: false,
    track_hover: true,
    visible: microphone.active});

**Comment by wbolster** [comment]
thanks for testing that out! care to make a pull request?

**Comment by rudolfkastl** [comment]
Pull request created: https://github.com/wbolster/nothing-to-say/pull/20

Note that this makes it work, but i am not sure if thats the correct fix :)

Thank you for considering the input!
