### ISSUE TITLE
Last version is not working with Gnome 3.36.6

### ISSUE THREAD

**Issue by exapsy** [wbolster/nothing-to-say#21]
When installing, it displays "error". Not sure how to debug to send out more information.

## Details

**OS Name:** Manjaro Linux: Build ID: rolling
**Gnome:** 3.36.6

**Comment by szpak** [comment]
`journalctl -b` and search for "nothing-to-say" (e.g. `/nothing`) in the stacktrace.

Grepping would be better, but it would not cover whole stacktraces. Maybe there is any better way.

**Comment by wbolster** [comment]
the only actual code changes since the previous version are two deleted lines; see #20 

on my archlinux system with this version:

```
$ gnome-shell --version
GNOME Shell 3.36.6
```

... it seems to work.

**Comment by wbolster** [comment]
looking at my own `journalctl` logs, i did see a warning, which i fixed just now: 917c6796be060b1e9dc656304e6743072a71af64

i've just uploaded a new version to https://extensions.gnome.org/ which should be approved and available soon

**Comment by exapsy** [comment]
@wbolster Ahah! I found out. I'm really sorry, I lost the exact text of the error.
What it said was
```
JS Error! Different version loaded from previous. Logout to load the current one
```
I wonder why did that happen though, since I rarely have to logout for a new version to be correctly loaded.

**Comment by exapsy** [comment]
> looking at my own `journalctl` logs, i did see a warning, which i fixed just now: [917c679](https://github.com/wbolster/nothing-to-say/commit/917c6796be060b1e9dc656304e6743072a71af64)

From what I see, the commit is related to the error. So, I'll just wait for GNOME to update the extension, and give feedback if it doesn't still work. Good job btw!

**Comment by wbolster** [comment]
thanks for the details, and for the kind words. let's see if the latest version works for you 🤞

**Comment by exapsy** [comment]
It took a while, and for a moment Gnome's Extension Page didn't work at all. But now it works!

**Comment by exapsy** [comment]
It took a while, but now it works.

Although, to update it without an error, I've had to follow one of the comments' suggestion in here
[https://extensions.gnome.org/extension/1113/nothing-to-say/](https://extensions.gnome.org/extension/1113/nothing-to-say/)

```
p1zz4br0etch3n:
just restart gnome-shell by Alt+F2 -> type "r" -> Enter
After that the error is gone
```

**Comment by wbolster** [comment]
cool, solved. not sure what caused the error, the extension changes are very minimal.
