### ISSUE TITLE
setting to show icon at all times

### ISSUE THREAD

**Issue by herrenP** [wbolster/nothing-to-say#24]
Thanks for the great extension. I would prefer to have the icon shown at all times though so I can rest assured it is disabled even when not using an application that want to use the microphone. Maybe add it as an option in dconf?

**Comment by herrenP** [comment]
I guess this is a clone of point bullet 1 in https://github.com/wbolster/nothing-to-say/issues/1#issuecomment-258886918.

**Comment by BenignBeppe** [comment]
This was fixed by #27, right?

**Comment by wbolster** [comment]
yes, it should be!
