### ISSUE TITLE
OSD show incorrect volume if user mute/unmute fast enough

### ISSUE THREAD

**Issue by herrenP** [wbolster/nothing-to-say#25]
Minor issue where the OSD show the volume as zero if the user mute and then umute very quickly.

```
➜ cat /usr/share/gnome/gnome-version.xml
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>38</minor>
 <micro>2</micro>
 <distributor>Arch Linux</distributor>
 <!--<date></date>-->
</gnome-version>
```

**Comment by wbolster** [comment]
i've seen this occasionally as well; i guess it's a race condition between the (un)mute action, which causes the level value to become zero (or nonzero)
