### ISSUE TITLE
Move icon to the center of the top bar

### ISSUE THREAD

**Issue by Jaime-Burgos** [wbolster/nothing-to-say#26]
I have lots of icons all in the right part of the top bar, and I'd like to move some of them (like this one) to the center. 

Would it be easy for you to add an option for this? 

Thanks a lot for your work!!

**Comment by wbolster** [comment]
tbh, i'd like to keep it simple. 

the latest version turns red red when the microphone active. i think that's a better approach to attract the right level of attention.

what do you think?

**Comment by Jaime-Burgos** [comment]
Hi @wbolster! Sure, that is a good enhacement, thanks!
