### ISSUE TITLE
no osd when clicking icon in top bar with mouse

### ISSUE THREAD

**Issue by wbolster** [wbolster/nothing-to-say#3]
clicking the icon is an explicit user interaction, with a visible result, because the icon changes. that means the osd is overkill.

when pressing the shortcut key, the osd is the right ui pattern, because the icon change will be barely noticable. and for push to talk it is a must-have.

**Comment by semente** [comment]
By the way,  my keyboard has a key to turn microphone on/off. GNOME understand it and display a OSD that looks almost like yours. Perhaps you would use GNOME owns support to trigger mute/unmute/OSD instead. It may increase code compatibility for the next GNOME releases and reduce your code and maintenance.

It is curious GNOME do not offer a shortcut option to the mute/unmute key in its shortcut preferenes but support and displays OSD notifications for them. It is the same for screen brightness adjustment keys.
