### ISSUE TITLE
Icon on top bar is the same when muted or unmuted

### ISSUE THREAD

**Issue by koshyviv** [wbolster/nothing-to-say#31]
So as the title says, the icon does not change. So I'm not able to verify if I'm currently muted or not.

This is how it looks when muted:
![image](https://user-images.githubusercontent.com/32818583/106473017-48f2ae00-64c9-11eb-990e-d1e185c946ed.png)

This when unmuted:
![image](https://user-images.githubusercontent.com/32818583/106473070-5dcf4180-64c9-11eb-9109-783eb319b5fb.png)

Could you let me know how i can debug this issue?

Details:
OS - Ubuntu 20.04.2 LTS
Gnome Version - 3.36.8

**Comment by wbolster** [comment]
maybe this is a problem with your theme? it shows up correctly for me. also in the osd (on screen display, the large popup thingy); how does that look for you?

**Comment by koshyviv** [comment]
So i do see the OSD correctly, it does show up. 
The issue that I'm facing is that, by looking at my screen i have no way to tell if I'm currently muted or not - 
I think this used to show up in my previous laptop, there used to be a slash across the mic icon when muted, so I'm not sure if I'm missing out on something

https://user-images.githubusercontent.com/32818583/107039697-3d162d00-67e4-11eb-918a-9f7133122bb9.mp4

**Comment by wbolster** [comment]
again, this may be an icon theme issue. the extension uses (should use?) the `microphone-sensitivity-high-symbolic` and `microphone-sensitivity-muted-symbolic` icons, and that results in the right icons, at least with the default Adwaita on my machine.

**Comment by koshyviv** [comment]
Ah, you are right - my icon theme (McMojave Circle) was interfering with it. It has the same icon for the labels you mentioned. Thank you!

**Comment by wbolster** [comment]
glad you sorted it out! maybe file a bug for the theme: it's apparently using the wrong icon for `microphone-sensitivity-muted-symbolic`

**Comment by koshyviv** [comment]
You're right, have filed a [bug](https://github.com/keeferrourke/la-capitaine-icon-theme/issues/585) for it, Thanks!
