### ISSUE TITLE
Correct way to write hotkey to change default

### ISSUE THREAD

**Issue by Leothi** [wbolster/nothing-to-say#35]
Hello!

In the README, you show an example of how to change the default hotkey for muting the mic
 `dconf write /org/gnome/shell/extensions/nothing-to-say/keybinding-toggle-mute '["<Super>backslash", "Pause"]'
`

How is the correct way to write these hotkeys? Im trying to change to ctrl+shift+Z but i cant. 
Can you help me?

**Comment by wbolster** [comment]
you can use the preference pane to set it via the gui:

![image](https://user-images.githubusercontent.com/748944/109045329-b9a97680-76d3-11eb-82b3-3e026e42e4a3.png)

if you want to use the command line, this works for me:

```
dconf write /org/gnome/shell/extensions/nothing-to-say/keybinding-toggle-mute '["<Control><Shift>Z"]'
```

see this for more info
https://developer.gnome.org/meta/stable/MetaDisplay.html#meta-display-add-keybinding
