### ISSUE TITLE
Icon missing from top bar after restart

### ISSUE THREAD

**Issue by lionipsum** [wbolster/nothing-to-say#39]
After I installed from gnome.org (with browser extension), I had the icon at the top bar and everything was working perfectly.
After a restart the icon is missing.
However, the keyboard shortcut still works to mute, un-mute and ptt.
Any ideas about how I can get the icon back?

System information:
OS: Ubuntu 20.04.2 LTS 64bit
Gnome Version: 3.36.8
Windowing System: X11

**Comment by wbolster** [comment]
try the setting?

**Comment by lionipsum** [comment]
> try the setting?

Oh my god. I have it turned back on Now. Thank you. 

Still, though, why did the state change?

**Comment by wbolster** [comment]
🤔 it didn't? or at least shouldn't. 😂

or maybe the default changed when the setting for introduced? did you recently upgrade?
