### ISSUE TITLE
Please add an option to hide the microphone icon from the gnome tray.

### ISSUE THREAD

**Issue by marbogd** [wbolster/nothing-to-say#41]
It really messes with my head having two of the same icons.

**Comment by wbolster** [comment]
what really messes with _my_ head is when internet randos slide into my notifications with nothing but a snarky comment

… for a feature that's already implemented and also tracked/mentioned in at least 3 places in this very same issue tracker, as a 10 second search would've revealed:

- https://github.com/wbolster/nothing-to-say/issues/24
- https://github.com/wbolster/nothing-to-say/pull/27
- https://github.com/wbolster/nothing-to-say/pull/29

**Comment by marbogd** [comment]
I kind of wanted to have my cake and eat it too, being able to only see the icon of the extension while hiding the default gnome one so I would be able to mute myself by clicking instead of a keyboard shortcut.

**Comment by marbogd** [comment]
Also, thanks for making this extension, found it today at work and it's really useful for what I do. Maybe for coders and people that do their work from the keyboard the feature I asked about would be useless, but I gotta hold my right hand on the mouse most of the time, so this feature would be really useful. Sorry to bother you.

**Comment by wbolster** [comment]
there are various extensions to modify the appearance of the top right menu and its icons (wifi, power, etc). maybe some combination of extensions achieves what you want.

(tweaking existing gnome components is notoriously tricky since there are often changes between releases, and extensions can easily step on each other's toes.)

**Comment by marbogd** [comment]
there is literally no extension which allows me to modify aggregate menu, only hide it as a hole

**Comment by wbolster** [comment]
then my suggestion would be to configure this extension to only show the icon when an app is recording. the result is that a red 🎙 icon appears/disappears whenever the microphone is (de)activated.

assuming you're not recording/teleconferencing most of the time, there would typically just be a single mic icon in the panel

**Comment by marbogd** [comment]
Thanks for the suggestion. I have been digging around the gnome extensions website and have tried pretty much any extension related to icons or the top right menu. Luckily, I've come across either a bug in the  "Volume Mixer" extension, or a bug that appeared after having a lot of active extensions, and the microphone button has disappeared. 
I am guessing it's a bug since there is no option to disable the original microphone icon, and there's also a empty space where the icon would be. I haven't written anything since college but I guess this is a case where it's not a bug, it's  a feature.
https://imgur.com/a/usjMn6R

**Comment by wbolster** [comment]
> why do you care so much about an internet rando?

because oss maintainer burnout is real, and base attitudes matter a lot.

(even an intermittent stream of ‘micro annoyances’ eventually adds up over the years; ~20y in my case)
