### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by cyrilf** [wbolster/nothing-to-say#47]
Since the last updates from yesterday (16/02) and `v13`, this extension is in error state with the following message:
"Error loading extension".

I'm using `GNOME Shell 3.36.9` and extension version 13.
Before that it was always working (and a huge thanks for that!)

View from Gnome Tweak Tools:
![Screenshot from 2022-02-17 08-08-16](https://user-images.githubusercontent.com/1302282/154423572-137ecf4a-222b-408a-b82e-fbd727b88e2c.png)

----

View from extensions.gnome.org
![Screenshot from 2022-02-17 08-08-53](https://user-images.githubusercontent.com/1302282/154423679-382c91cb-a996-4e32-a093-9b2dc9026bc0.png)

----

Let me know if you need more info/log (and how to find them).

Thanks!

**Comment by cyrilf** [comment]
Thanks for the `journalctl /usr/bin/gnome-shell` tip.

It helped me find this [issue](https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/134) which had the same error message as I did (on a different extension).

Deleting the extension and then rebooting my laptop ([as suggested in this comment](https://github.com/OttoAllmendinger/gnome-shell-screenshot/issues/134#issuecomment-728331206)) solved my issue.

It now works seemlessly.. :tada:
Thanks for your reactivity! :sparkles: 

---

_the goold old reboot-solve-everything-trick_ :see_no_evil:

**Comment by juanriqu** [comment]
> reopening b/c #48 by @juanriqu
> 
> needs more info though.

What type of info? I don't know what type how I can find it.
Please say me I don't know to much about gnome yet.

**Comment by cyrilf** [comment]
@juanriqu 
For your info, what I did was:
- remove the extension (click on the red cross on the gnome extension website)
- run `journalctl -f /usr/bin/gnome-shell` on a terminal
- install the extension again
- look at the error being displayed on the terminal

**Comment by tonybolzan** [comment]
I have a problem with update this week (14~18 Feb 2022) because a new dependency added to project 

**Error message**
```
Requiring GstAudio, version none: Typelib file for namespace 'GstAudio' (any version) not found
```
**Solution**
```sh
sudo apt install gir1.2-gst-plugins-base-1.0
```
**Environment**
- Ubuntu 21.10 Minimal Install
- gnome-shell 40.5
- Extension metadata.json version: 14

**Comment by juanriqu** [comment]
> @cyrilf
> 
>     * reboot before doing anything below
> 
>     * open a terminal, run `$ journalctl -b -f /usr/bin/gnome-shell`
> 
>     * open the extensions UI, enable the extension
> 
>     * watch the output and check what error is reported
It gave me this error in extensions app, cant enable the extensions, 
Requiring GstAudio, version none: Typelib file for namespace 'GstAudio' (any version) not found

**Comment by juanriqu** [comment]
Solved by installing
sudo apt install gir1.2-gst-plugins-base-1.0, Thanks for all the help, now it works

**Comment by wbolster** [comment]
this is now also mentioned in the readme
