### ISSUE TITLE
Extension just broke with today's upgrade on Ubuntu 20.04.4 LTS

### ISSUE THREAD

**Issue by recw** [wbolster/nothing-to-say#57]
Today I received an upgrade notification. Upon executing the upgrade the extension was disabled and I now cannot be enabled anymore. Instead of the on/off toggle switch on the gnome extensions web interface there is just a red ERROR label without any further information what went wrong.
Removing and reinstalling the extension leads to the same ERROR label.
![Screenshot from 2022-05-13 15-21-34](https://user-images.githubusercontent.com/36105158/168293049-c23217f1-5a8c-45db-81ac-fa83809a6993.png)

Is there any way to revert to the previous version of this extension?

**Comment by recw** [comment]
ahh, nevermind :facepalm: The issue did indeed resolve after a reboot. My bad, should have tried the primary solution to all computer problems.
However, I couldn't find any "JS ERROR" in the syslog.
Anyway, thanks for the support and the great piece of software!

**Comment by wbolster** [comment]
no errors in logs is actually good 🙃

requiring a restart when upgrading enabled extensions has a bit weird UX indeed, it should preferably just tell you to re-login
