### ISSUE TITLE
Not working 22.04 LTS

### ISSUE THREAD

**Issue by Rodscaloppe** [wbolster/nothing-to-say#59]
Not working, shows error in extension manager "playbin.set_volume is not a function"
Pop!_OS 22.04 LTS X11

do you know what the problem is? can i fix it?

Thanks

**Comment by drupov** [comment]
I have the same error. Also on Ubuntu 22.04 LTS

**
![image](https://github.com/wbolster/nothing-to-say/assets/1836325/276e79d0-7af8-4554-af04-ca9c1c526d73)
**
