### ISSUE TITLE
Icon disappeared from topbar

### ISSUE THREAD

**Issue by semente** [wbolster/nothing-to-say#6]
The icon just disappeared but the extension is active and push-to-talk shortcut is working. I don't know yet what happened to it disappear. I will restart my GNOME session to see if it back and I will try to reproduce the issue.

**Comment by semente** [comment]
Just confirming, the indicator do not show up anymore even after I've reinstalled it and restarted the session. Do you know how could I debug it?

**Comment by semente** [comment]
Found the issue! And that is weird. When I start up a VirtualBox machine it appears, when I turn it off it disappears. :P

**Comment by wbolster** [comment]
hmm, strange. the show/hide logic is hooked onto pulseaudio events through gnome-volume-control.

you do realise that the icon is only supposed to be visible when an application is recording? try to record with the gnome sound recorder and see whether you see the icon and the osd notification.

**Comment by semente** [comment]
oh, I see! sorry, when I installed it I had some VMs open so I thought it was the normal behavior. It works when I record something. You can close this issue if you wish or perhaps you want investigate it to avoid it happening when a vbox VM is running. Let me know if I can help with some debug information.

I've installed this extension for other purposes. I would be sure my mic is always muted. I like the idea to have "the hold to talk" feature, it is amazing, some softwares has it built-in it but not all. But if you are planning to add a preferences panel, consider adding the feature of always have the indicator visible.

I wish to have time to learn how to write GNOME extensions and help you but at moment is complicated. Thanks!

(I will add this and another option I would see in the preferences panel in the issue #1 :)

**Comment by wbolster** [comment]
ok great. i'll close this issue since the remaining points are tracked in #1.

thanks a lot for your contribution!
