### ISSUE TITLE
gnome 43.2 wayland gdm login problems with activated extension

### ISSUE THREAD

**Issue by mlario** [wbolster/nothing-to-say#63]
On gnome 43.2 I'm unable to login using gdm into wayland session when extension is activated:

after inputting password, gdm screen freezes and does not proceed to desktop + keyboard freezes too so I cannot switch to TTY with Ctrl+Alt+F2
I can only hard reset computer

version of extension: 17

login into x.org session works fine

when I deactivate extension I can again login into wayland session

**Comment by wbolster** [comment]
weird, can you check logs when it happens?

**Comment by mlario** [comment]
here is gdm log:

[gdm.greeter.log](https://github.com/wbolster/nothing-to-say/files/10369079/gdm.greeter.log)


I noticed issue on gentoo open-rc gnome 43.2 wayland session
on fedora systemd gnome 43.2  wayland session I did not see any issue so there might be distribution-dependendent differences

**Comment by wbolster** [comment]
i don't see anything related to this extension in those logs. can you read more logs, likely those from your user session, and see if you can find any messages related to this extension? please share only relevant snippets if you manage to find them 🙏
