### ISSUE TITLE
Please update Gnome 44, thanks.

### ISSUE THREAD

**Issue by JerryPenguin** [wbolster/nothing-to-say#66]
Please update Gnome 44, thanks.

**Comment by arantes555** [comment]
in the meantime, you can just `nano ~/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee/metadata.json`, add `"44"` to the array of supported `shell-versions`, log-out and back in, and you're good to go :)

**Comment by wbolster** [comment]
thanks for confirming that it works on gnome 44

**Comment by wbolster** [comment]
new v18 version available from extensions.gnome.org
