### ISSUE TITLE
Gnome 45

### ISSUE THREAD

**Issue by mo8it** [wbolster/nothing-to-say#67]
Port to Gnome 45? 😍

Thanks for this awesome extension ❤️

**Comment by axxapy** [comment]
Opened PR https://github.com/wbolster/nothing-to-say/pull/68

to use it immediately, before PR is merged:
```
rm -rf ~/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee
git clone --depth 1 https://github.com/axxapy/nothing-to-say
```

After PR is merged, remove github version and reinstall via extensions.gnome.org
```
rm -rf ~/.local/share/gnome-shell/extensions/nothing-to-say@extensions.gnome.wouter.bolsterl.ee
```

**Comment by wbolster** [comment]
closed via #68

**Comment by wbolster** [comment]
keeping open until this is available from https://extensions.gnome.org/extension/1113/nothing-to-say/

turns out this also needed #69

**Comment by wbolster** [comment]
v20 with gnome 45 support is now available from https://extensions.gnome.org/extension/1113/nothing-to-say/
