### ISSUE TITLE
Doesn't work in Overview

### ISSUE THREAD

**Issue by vuntz** [wbolster/nothing-to-say#7]
For some reason, the keybinding doesn't work when using the Overview of the shell. This is actually quite bad when using PTT and moving to the Overview as it cuts you out.

**Comment by wbolster** [comment]
gnome shell keybindings do not work in overview mode, i think. not sure what extensions can do about this...

**Comment by wbolster** [comment]
maybe this is possible after all using `SHELL_ACTION_MODE_OVERVIEW`

https://developer.gnome.org/shell/stable/shell-shell-action-modes.html

**Comment by wbolster** [comment]
it works indeed! it took only 4 years to discover this... 😬
