### ISSUE TITLE
add support for gnome 46

### ISSUE THREAD

**Issue by TheWiseNoob** [wbolster/nothing-to-say#73]
Can you please add Gnome 46 support?

Thanks <3

**Comment by wbolster** [comment]
do you happen to know whether the current code actually works?

(change the version field in metadata.json in `~/.local/share/gnome-shell/extensions/…`, then logout+login)

**Comment by wbolster** [comment]
turns out the answer seems yes. (on gnome 46 myself now)

**Comment by wbolster** [comment]
i've uploaded a new release to https://extensions.gnome.org/ just now. should appear soon 🤞🏼

**Comment by TheWiseNoob** [comment]
Thank you! I'm only on Gnome 45 right now, so I wouldn't have been of much help.
