### ISSUE TITLE
Doesn't appear to work in Gnome 3.22.1

### ISSUE THREAD

**Issue by atmarx** [wbolster/nothing-to-say#9]
Installed and enabled, but doesn't appear in the top bar.

**Comment by wbolster** [comment]
did you read the readme? https://github.com/wbolster/nothing-to-say/

**Comment by atmarx** [comment]
Got it.  I didn't read that to mean it _wouldn't_ show when it wasn't recording, but that's my fault.  Maybe a subpoint to explicitly list that it won't display when nothing is recording.  I consider that a neat feature since it doesn't clutter up the bar when it's not useful.  Thanks for the pointer (and the extension!)

**Comment by wbolster** [comment]
you're welcome :)
